name: GitOps

###
# GitOps - automatic infrastructure management GitHub Action
#
# See https://docs.nubesgen.com/gitops/gitops-quick-start/
# for more information about using GitOps with NubesGen.
###

on:
  push:
    branches:
      - 'env-*'

env:
  NODEJS_VERSION: '16'
  APP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root

jobs:
  manage-infrastructure:
    runs-on: ubuntu-20.04
    outputs:
      application_name: ${{ steps.infrastructure-deployment.outputs.application_name }}
      application_url: ${{ steps.infrastructure-deployment.outputs.application_url }}
      resource_group: ${{ steps.infrastructure-deployment.outputs.resource_group }}
    steps:
      - name: Apply Bicep configuration
        id: infrastructure-deployment
        uses: microsoft/nubesgen-actions/gitops-apply-bicep@v0.10.0
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          project_name: 'contoso-t4j'
          deployment_region: 'eastus2'
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Build a NodeJS project
        uses: microsoft/nubesgen-actions/gitops-build-nodejs@v0.10.0
        with:
          nodejs_version: ${{ env.NODEJS_VERSION }}
          application_package_path: ${{ env.APP_PACKAGE_PATH }}
  deploy:
    needs: [manage-infrastructure, build]
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy a NodeJS application to Azure App Service
        uses: microsoft/nubesgen-actions/gitops-deploy-to-app-service-nodejs@v0.10.0
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          application_name: ${{ needs.manage-infrastructure.outputs.application_name }}
  display-information:
    needs: [manage-infrastructure]
    runs-on: ubuntu-20.04
    steps:
      - name: Display Azure infrastructure information
        uses: microsoft/nubesgen-actions/gitops-display-information@v0.10.0
        with:
          application_name: ${{ needs.manage-infrastructure.outputs.application_name }}
          application_url: ${{ needs.manage-infrastructure.outputs.application_url }}
          resource_group: ${{ needs.manage-infrastructure.outputs.resource_group }}
